const serif = { fontFamily: "'Bricolage Grotesque', sans-serif" }
const sans = { fontFamily: "'Geist', sans-serif" }

/**
 * Hero sample report — static, document-style.
 *
 * Primary hero visual on the landing page. Reads like a finished written
 * briefing, not a dashboard. No toggles, charts, KPI panels, or analytics
 * views — just the four narrative sections of a real generated report.
 */

const NARRATIVE = 'Performance improved this month, driven by stronger efficiency in high-intent campaigns and improved allocation of spend toward converting traffic.'

const HEADLINE_BULLETS = [
  'Conversions increased 18%',
  'CPA decreased 11%',
  'Brand campaigns outperformed non-brand traffic',
]

const KEY_TAKEAWAY = 'Performance gains were driven by efficiency improvements rather than increased spend.'

const DRIVERS = [
  'Improved efficiency in branded search campaigns',
  'Reduced spend on low-intent keyword traffic',
  'Stronger conversion performance in remarketing segments',
]

const EXPLAIN_QUOTES = [
  'We improved efficiency this month without increasing your budget.',
  "We're seeing stronger performance from higher-intent search traffic.",
  'The account is becoming more efficient as we refine spend allocation.',
]

const TALKING_POINTS = [
  'This month is about efficiency gains, not just volume.',
  "We're improving how budget is allocated across intent levels.",
  'The account is trending toward higher-quality traffic overall.',
]

function Eyebrow({ color = '#94A3B8', children }) {
  return (
    <div style={{
      ...sans, fontSize: 9, fontWeight: 600,
      textTransform: 'uppercase', letterSpacing: '0.10em',
      color, marginBottom: 6,
    }}>
      {children}
    </div>
  )
}

export default function HeroTransformation() {
  return (
    <div style={{
      background: '#FAFAF9',
      border: '1px solid rgba(255,255,255,0.12)',
      borderRadius: 14,
      overflow: 'hidden',
      boxShadow: '0 20px 50px -20px rgba(0,0,0,0.6)',
    }}>
      {/* Top accent + meta strip */}
      <div style={{ height: 3, background: '#2563EB' }} />
      <div style={{
        padding: '11px 18px',
        borderBottom: '1px solid #F1F5F9',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: '#FFFFFF',
      }}>
        <span style={{
          ...sans, fontSize: 11, fontWeight: 500, color: '#1E293B',
          display: 'flex', alignItems: 'center', gap: 8,
        }}>
          <span style={{
            width: 7, height: 7, borderRadius: '50%',
            background: '#2563EB', flexShrink: 0,
          }} />
          Apex Digital · April 2025
        </span>
        <span style={{ ...sans, fontSize: 10, color: '#94A3B8' }}>
          Generated by retainr · 47 sec
        </span>
      </div>

      {/* Document body */}
      <div style={{ padding: '18px 20px', display: 'flex', flexDirection: 'column', gap: 14 }}>

        {/* 1. Performance Narrative */}
        <section>
          <Eyebrow>Monthly Performance Narrative</Eyebrow>
          <p style={{
            ...serif, fontSize: 13.5, fontStyle: 'italic',
            lineHeight: 1.65, color: '#1E293B',
            borderLeft: '2px solid #2563EB', paddingLeft: 12,
            margin: 0,
          }}>
            "{NARRATIVE}"
          </p>
          <ul style={{
            listStyle: 'none', padding: 0,
            margin: '10px 0 0 0',
            display: 'flex', flexDirection: 'column', gap: 5,
          }}>
            {HEADLINE_BULLETS.map((b) => (
              <li key={b} style={{
                ...sans, fontSize: 11.5, color: '#334155',
                display: 'flex', gap: 7, lineHeight: 1.55,
              }}>
                <span style={{ color: '#2563EB', flexShrink: 0 }}>•</span>{b}
              </li>
            ))}
          </ul>
        </section>

        {/* Key takeaway */}
        <div style={{
          borderLeft: '2px solid #15803D',
          background: '#F0FDF4',
          padding: '9px 12px',
        }}>
          <Eyebrow color="#15803D">Key takeaway</Eyebrow>
          <div style={{
            ...sans, fontSize: 11.5, lineHeight: 1.55,
            color: '#14532D',
          }}>
            {KEY_TAKEAWAY}
          </div>
        </div>

        {/* 2. Drivers */}
        <section>
          <Eyebrow>What drove performance changes</Eyebrow>
          <ul style={{
            listStyle: 'none', padding: 0, margin: 0,
            display: 'flex', flexDirection: 'column', gap: 5,
          }}>
            {DRIVERS.map((d) => (
              <li key={d} style={{
                ...sans, fontSize: 11.5, color: '#334155',
                display: 'flex', gap: 7, lineHeight: 1.55,
              }}>
                <span style={{ color: '#94A3B8', flexShrink: 0 }}>→</span>{d}
              </li>
            ))}
          </ul>
        </section>

        {/* 3. Client explanations */}
        <div style={{
          borderLeft: '2px solid #2563EB',
          background: '#EFF6FF',
          padding: '9px 12px',
        }}>
          <Eyebrow color="#1D4ED8">How to explain this to the client</Eyebrow>
          {EXPLAIN_QUOTES.map((q) => (
            <div key={q} style={{
              ...serif, fontSize: 12.5, fontStyle: 'italic',
              lineHeight: 1.55, color: '#1E3A5F',
              marginTop: 4,
            }}>
              "{q}"
            </div>
          ))}
        </div>

        {/* 4. Talking points */}
        <div style={{
          borderLeft: '2px solid #D97706',
          background: '#FFFBEB',
          padding: '9px 12px',
        }}>
          <Eyebrow color="#B45309">Talking points for client calls</Eyebrow>
          {TALKING_POINTS.map((t) => (
            <div key={t} style={{
              ...sans, fontSize: 11.5, lineHeight: 1.55,
              color: '#78350F',
              marginTop: 3, display: 'flex', gap: 7,
            }}>
              <span style={{ color: '#D97706', flexShrink: 0 }}>›</span>"{t}"
            </div>
          ))}
        </div>

      </div>

      {/* Footer with shareable framing — reinforces the comm-output positioning */}
      <div style={{
        borderTop: '1px solid #F1F5F9',
        padding: '10px 18px',
        background: '#FFFFFF',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        gap: 10, flexWrap: 'wrap',
      }}>
        <span style={{ ...sans, fontSize: 10, color: '#94A3B8' }}>
          Read-only · share with client or team
        </span>
        <span style={{
          ...sans, fontSize: 10, color: '#2563EB',
          display: 'inline-flex', alignItems: 'center', gap: 4,
        }}>
          ↗ retainr.io/r/demo
        </span>
      </div>
    </div>
  )
}
