import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import Logo from '../components/Logo'

/* ─────────── Design tokens ─────────── */

const F = { sans: { fontFamily: "'DM Sans', system-ui, -apple-system, sans-serif" } }

const C = {
  bg:      '#FFFFFF',
  bgAlt:   '#F8FAFC',
  text:    '#0F1F3D',
  muted:   '#64748B',
  subtle:  '#94A3B8',
  border:  '#E2E8F0',
  accent:  '#04256c',
  positive: '#10B981',
  amber:   '#F59E0B',
  navy:    '#0F1F3D',
}

const PAGE_CSS = `
  html, body { background: ${C.bgAlt}; }
  * { box-sizing: border-box; }

  .sr-nav { background: rgba(255,255,255,0.8); border-bottom: 1px solid transparent; transition: background 0.2s, border-color 0.2s; }
  .sr-nav.scrolled { background: rgba(255,255,255,0.94); border-bottom-color: ${C.border}; backdrop-filter: blur(12px); }

  .sr-nav-link { padding: 6px 12px; border-radius: 7px; color: ${C.muted}; text-decoration: none; font-size: 14px; font-weight: 500; transition: background 0.15s, color 0.15s; }
  .sr-nav-link:hover { background: ${C.bgAlt}; color: ${C.text}; }

  .sr-report-card { background: ${C.bg}; border-radius: 16px; border: 1px solid ${C.border}; overflow: hidden; box-shadow: 0 2px 12px rgba(15,31,61,0.05); }
  .sr-view-btn { padding: 11px 22px; border-radius: 9px; border: 1.5px solid ${C.accent}; background: ${C.bg}; color: ${C.accent}; font-size: 14px; font-weight: 700; cursor: pointer; font-family: 'DM Sans', sans-serif; transition: all 0.15s; }
  .sr-view-btn:hover { background: ${C.accent}; color: #fff; }

  .sr-metric-card { background: #fff; border: 1px solid #E8ECF2; border-radius: 10px; padding: 10px 14px; display: flex; flex-direction: column; gap: 2px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }

  @media (max-width: 900px) {
    .sr-card-grid { grid-template-columns: 1fr !important; }
    .sr-preview-col { display: none !important; }
  }
  @media (max-width: 640px) {
    .sr-modal-metrics { grid-template-columns: repeat(2, 1fr) !important; }
  }
`

/* ─────────── Preview components ─────────── */

function SparkLine({ color = C.accent, up = true }) {
  const pts = up
    ? '0,40 15,35 30,28 45,32 60,20 75,15 90,10 105,5'
    : '0,10 15,15 30,20 45,14 60,25 75,30 90,22 105,35'
  const gId = `sg_${color.replace('#', '')}_${up}`
  return (
    <svg width={106} height={44} style={{ display: 'block' }}>
      <defs>
        <linearGradient id={gId} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={color} stopOpacity="0.18" />
          <stop offset="100%" stopColor={color} stopOpacity="0" />
        </linearGradient>
      </defs>
      <polygon points={`0,44 ${pts} 105,44`} fill={`url(#${gId})`} />
      <polyline points={pts} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function MetricPill({ label, value, delta, color = C.positive }) {
  return (
    <div className="sr-metric-card">
      <span style={{ ...F.sans, fontSize: 11, color: C.subtle, fontWeight: 500, letterSpacing: '0.04em', textTransform: 'uppercase' }}>{label}</span>
      <span style={{ ...F.sans, fontSize: 20, fontWeight: 700, color: C.text, lineHeight: 1.2 }}>{value}</span>
      {delta && <span style={{ ...F.sans, fontSize: 11, color, fontWeight: 600 }}>{delta}</span>}
    </div>
  )
}

function ClientReportPreview() {
  return (
    <div style={{ background: C.bgAlt, borderRadius: 12, border: `1px solid ${C.border}`, overflow: 'hidden', boxShadow: '0 4px 16px rgba(15,31,61,0.08)' }}>
      {/* Browser chrome */}
      <div style={{ background: '#fff', borderBottom: `1px solid ${C.border}`, padding: '10px 14px', display: 'flex', alignItems: 'center', gap: 8 }}>
        <div style={{ display: 'flex', gap: 5 }}>
          {['#FF5F57', '#FFBD2E', '#28C840'].map(c => <div key={c} style={{ width: 9, height: 9, borderRadius: '50%', background: c }} />)}
        </div>
        <div style={{ flex: 1, background: '#F1F5F9', borderRadius: 5, height: 18, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <span style={{ ...F.sans, fontSize: 9, color: C.subtle }}>retainr.io — Client Report · Apex Digital · April 2025</span>
        </div>
      </div>
      <div style={{ padding: '14px 14px 0' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
          <div>
            <div style={{ ...F.sans, fontSize: 10, color: C.subtle, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase', marginBottom: 2 }}>Monthly Performance Report</div>
            <div style={{ ...F.sans, fontSize: 14, fontWeight: 700, color: C.text }}>Apex Digital Co.</div>
            <div style={{ ...F.sans, fontSize: 11, color: C.muted }}>April 1 – April 30, 2025</div>
          </div>
          <div style={{ background: `${C.accent}15`, borderRadius: 7, padding: '4px 10px', ...F.sans, fontSize: 10, fontWeight: 600, color: C.accent }}>Generated by AI</div>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 12 }}>
          <MetricPill label="Impr." value="284K" delta="↑ 12.4%" color={C.positive} />
          <MetricPill label="Clicks" value="18.2K" delta="↑ 8.1%" color={C.positive} />
          <MetricPill label="Conv." value="412" delta="↑ 23.7%" color={C.positive} />
          <MetricPill label="CPC" value="$1.84" delta="↓ 6.2%" color={C.amber} />
        </div>
        <div style={{ background: '#fff', border: `1px solid ${C.border}`, borderRadius: 8, padding: '10px 12px 8px', marginBottom: 12 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <span style={{ ...F.sans, fontSize: 11, fontWeight: 600, color: C.text }}>Conversion Trend</span>
            <div style={{ display: 'flex', gap: 4 }}>
              {['7d', '30d', '90d'].map((t, i) => (
                <span key={t} style={{ ...F.sans, fontSize: 9, padding: '2px 6px', borderRadius: 3, background: i === 1 ? C.accent : '#F1F5F9', color: i === 1 ? '#fff' : C.muted, fontWeight: 600 }}>{t}</span>
              ))}
            </div>
          </div>
          <SparkLine color={C.accent} up={true} />
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 3 }}>
            {['Apr 1', 'Apr 8', 'Apr 15', 'Apr 22', 'Apr 30'].map(d => (
              <span key={d} style={{ ...F.sans, fontSize: 8, color: '#CBD5E1' }}>{d}</span>
            ))}
          </div>
        </div>
        <div style={{ background: `${C.accent}08`, border: `1px solid ${C.accent}22`, borderRadius: 8, padding: '10px 12px', marginBottom: 14 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
            <div style={{ width: 14, height: 14, borderRadius: 3, background: C.accent, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <svg width="8" height="8" viewBox="0 0 10 10" fill="none"><path d="M2 5h6M5 2v6" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" /></svg>
            </div>
            <span style={{ ...F.sans, fontSize: 9, fontWeight: 700, color: C.accent, letterSpacing: '0.05em', textTransform: 'uppercase' }}>AI Executive Summary</span>
          </div>
          <p style={{ ...F.sans, fontSize: 11, color: '#334155', lineHeight: 1.6, margin: 0 }}>
            <strong>April was your strongest month.</strong> Conversions jumped 23.7% while CPC fell 6.2%. The branded keyword campaign drove 38% of all conversions…
          </p>
        </div>
      </div>
    </div>
  )
}

function InternalReportPreview() {
  return (
    <div style={{ background: C.bgAlt, borderRadius: 10, border: `1px solid ${C.border}`, overflow: 'hidden' }}>
      <div style={{ background: C.navy, padding: '12px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <div style={{ ...F.sans, fontSize: 10, color: 'rgba(255,255,255,0.45)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Internal Analysis</div>
          <div style={{ ...F.sans, fontSize: 14, fontWeight: 700, color: '#fff', marginTop: 1 }}>Apex Digital · April 2025</div>
        </div>
        <div style={{ background: 'rgba(255,255,255,0.08)', borderRadius: 6, padding: '4px 10px', ...F.sans, fontSize: 10, fontWeight: 700, color: 'rgba(255,255,255,0.6)' }}>Confidential</div>
      </div>
      <div style={{ padding: '12px 14px', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6 }}>
        <MetricPill label="Impressions" value="284K" delta="↑ 12.4%" />
        <MetricPill label="CTR" value="6.4%" delta="↑ 0.5pp" />
        <MetricPill label="Conv. Rate" value="2.3%" delta="↑ 0.4pp" />
        <MetricPill label="ROAS" value="4.2×" delta="↑ 0.6×" />
      </div>
      <div style={{ margin: '0 14px', borderRadius: 8, background: '#fff', border: `1px solid ${C.border}`, padding: '10px 12px', marginBottom: 14 }}>
        <div style={{ ...F.sans, fontSize: 10, fontWeight: 700, color: C.muted, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 8 }}>Conversion trend</div>
        <SparkLine color={C.accent} up={true} />
      </div>
      <div style={{ margin: '0 14px 14px', background: '#FEF3C7', border: '1px solid #FDE68A', borderRadius: 8, padding: '10px 12px' }}>
        <div style={{ ...F.sans, fontSize: 10, fontWeight: 700, color: C.amber, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 4 }}>⚠ Flag for team</div>
        <p style={{ ...F.sans, fontSize: 11, color: '#92400E', lineHeight: 1.5, margin: 0 }}>Display CPM rose 18% vs. last month — review placement exclusions before next cycle.</p>
      </div>
    </div>
  )
}

function ExecutiveSummaryPreview() {
  return (
    <div style={{ background: C.bgAlt, borderRadius: 10, border: `1px solid ${C.border}`, overflow: 'hidden' }}>
      <div style={{ background: `linear-gradient(135deg, ${C.accent} 0%, #0a3a8f 100%)`, padding: '16px 16px' }}>
        <div style={{ ...F.sans, fontSize: 10, color: 'rgba(255,255,255,0.5)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 }}>Executive Summary · Q1 2025</div>
        <div style={{ ...F.sans, fontSize: 16, fontWeight: 800, color: '#fff', lineHeight: 1.2 }}>Apex Digital Co.</div>
        <div style={{ display: 'flex', gap: 16, marginTop: 12 }}>
          {[['$41.2K', 'Total Spend'], ['1,184', 'Conversions'], ['4.1×', 'Avg ROAS']].map(([v, l]) => (
            <div key={l}>
              <div style={{ ...F.sans, fontSize: 18, fontWeight: 800, color: '#fff' }}>{v}</div>
              <div style={{ ...F.sans, fontSize: 9, color: 'rgba(255,255,255,0.5)', fontWeight: 600 }}>{l}</div>
            </div>
          ))}
        </div>
      </div>
      <div style={{ padding: '12px 14px' }}>
        <div style={{ ...F.sans, fontSize: 10, fontWeight: 700, color: C.muted, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 8 }}>Quarter highlights</div>
        {[
          'Conversions grew 31% YoY driven by new search campaigns',
          'Branded keyword ROAS exceeded 8× for the first time',
          'CPA decreased from $47 → $35 — 26% efficiency improvement',
        ].map((item, i) => (
          <div key={i} style={{ display: 'flex', gap: 8, alignItems: 'flex-start', marginBottom: 8 }}>
            <div style={{ width: 16, height: 16, borderRadius: '50%', background: `${C.positive}20`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 }}>
              <svg width="8" height="8" viewBox="0 0 8 8" fill="none"><path d="M1.5 4l1.5 1.5L6.5 2" stroke={C.positive} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
            </div>
            <span style={{ ...F.sans, fontSize: 11, color: '#334155', lineHeight: 1.5 }}>{item}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

/* ─────────── Modals ─────────── */

function ModalShell({ onClose, children, maxWidth = 680 }) {
  return (
    <div
      style={{ position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(15,31,61,0.65)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32 }}
      onClick={onClose}
    >
      <div
        style={{ background: '#fff', borderRadius: 16, maxWidth, width: '100%', maxHeight: '90vh', overflow: 'auto', boxShadow: '0 32px 80px rgba(15,31,61,0.28)' }}
        onClick={e => e.stopPropagation()}
      >
        {children}
      </div>
    </div>
  )
}

/* What the CLIENT receives — clean, polished, no internal content */
function ClientReportModal({ onClose }) {
  return (
    <ModalShell onClose={onClose}>
      {/* Header */}
      <div style={{ background: C.accent, padding: '20px 28px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 1 }}>
        <div>
          <div style={{ ...F.sans, fontSize: 11, color: 'rgba(255,255,255,0.5)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 2 }}>
            Monthly Performance Report · Sent to client
          </div>
          <div style={{ ...F.sans, fontSize: 20, fontWeight: 800, color: '#fff' }}>Apex Digital Co. · April 2025</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ background: '#10B98125', border: '1px solid #10B98140', borderRadius: 20, padding: '4px 12px', ...F.sans, fontSize: 11, fontWeight: 700, color: '#6EE7B7' }}>
            Delivered to client inbox
          </div>
          <button onClick={onClose} style={{ width: 32, height: 32, borderRadius: '50%', background: 'rgba(255,255,255,0.1)', border: 'none', color: '#fff', cursor: 'pointer', fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'sans-serif' }}>×</button>
        </div>
      </div>

      <div style={{ padding: '28px' }}>
        {/* "This is what the client sees" banner */}
        <div style={{ background: '#10B98110', border: '1px solid #10B98130', borderRadius: 10, padding: '10px 16px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 3C4.5 3 1.5 8 1.5 8s3 5 6.5 5 6.5-5 6.5-5S11.5 3 8 3z" stroke="#10B981" strokeWidth="1.5"/><circle cx="8" cy="8" r="2" stroke="#10B981" strokeWidth="1.5"/></svg>
          <span style={{ ...F.sans, fontSize: 13, fontWeight: 600, color: '#065F46' }}>This is exactly what your client receives — no internal notes, no agency prep.</span>
        </div>

        {/* Metrics */}
        <div className="sr-modal-metrics" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginBottom: 24 }}>
          {[
            { label: 'Impressions', value: '284K', delta: '↑ 12.4%', color: C.positive },
            { label: 'Clicks', value: '18.2K', delta: '↑ 8.1%', color: C.positive },
            { label: 'Conversions', value: '412', delta: '↑ 23.7%', color: C.positive },
            { label: 'Avg. CPC', value: '$1.84', delta: '↓ 6.2%', color: C.amber },
          ].map(m => (
            <div key={m.label} style={{ background: C.bgAlt, border: `1px solid ${C.border}`, borderRadius: 10, padding: '14px 16px' }}>
              <div style={{ ...F.sans, fontSize: 11, color: C.muted, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 4 }}>{m.label}</div>
              <div style={{ ...F.sans, fontSize: 24, fontWeight: 800, color: C.text, lineHeight: 1 }}>{m.value}</div>
              <div style={{ ...F.sans, fontSize: 12, color: m.color, fontWeight: 600, marginTop: 3 }}>{m.delta}</div>
            </div>
          ))}
        </div>

        {/* AI narrative */}
        <div style={{ background: `${C.accent}08`, border: `1px solid ${C.accent}22`, borderRadius: 12, padding: '18px 20px', marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <div style={{ width: 20, height: 20, borderRadius: 5, background: C.accent, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none"><path d="M2 5h6M5 2v6" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" /></svg>
            </div>
            <span style={{ ...F.sans, fontSize: 12, fontWeight: 700, color: C.accent, textTransform: 'uppercase', letterSpacing: '0.05em' }}>AI Executive Summary</span>
          </div>
          <p style={{ ...F.sans, fontSize: 14, color: '#334155', lineHeight: 1.7, marginBottom: 12 }}>
            <strong>April was your strongest month in 2025.</strong> Conversions jumped 23.7% while your cost-per-click fell 6.2% — meaning you're acquiring more customers at lower cost. That's a rare and impressive combination.
          </p>
          <p style={{ ...F.sans, fontSize: 14, color: '#334155', lineHeight: 1.7, marginBottom: 12 }}>
            The new branded keyword campaign launched March 28th was the clear standout, contributing <strong>38% of all conversions</strong> at a ROAS of 6.4× — well above your 4× target.
          </p>
          <p style={{ ...F.sans, fontSize: 14, color: '#334155', lineHeight: 1.7 }}>
            One area to watch: display CPM rose 18% vs. March. We're reviewing placement exclusions before the next cycle to keep overall efficiency on track.
          </p>
        </div>

        {/* What we're focused on next */}
        <div style={{ background: C.bgAlt, border: `1px solid ${C.border}`, borderRadius: 12, padding: '18px 20px', marginBottom: 20 }}>
          <div style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: C.text, marginBottom: 14 }}>What we're focused on next</div>
          {[
            { icon: '→', text: 'Scale the branded keyword campaign — propose a 20% budget increase based on 6.4× ROAS.' },
            { icon: '→', text: 'Audit display placement exclusions to bring CPM back in line before the May cycle.' },
            { icon: '→', text: 'Maintain Shopping campaign allocation, which drove the majority of conversion growth.' },
          ].map((item, i) => (
            <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', marginBottom: i < 2 ? 10 : 0 }}>
              <span style={{ ...F.sans, fontSize: 14, color: C.accent, fontWeight: 700, marginTop: 1 }}>{item.icon}</span>
              <span style={{ ...F.sans, fontSize: 14, color: '#334155', lineHeight: 1.55 }}>{item.text}</span>
            </div>
          ))}
        </div>

        {/* Sent via email note */}
        <div style={{ background: '#F0FDF4', border: '1px solid #BBF7D0', borderRadius: 10, padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: 18 }}>📧</span>
          <div>
            <div style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: '#065F46' }}>This report lands in your client's inbox</div>
            <div style={{ ...F.sans, fontSize: 12, color: '#16A34A', marginTop: 2 }}>No login required. No internal notes included. A shareable link is also generated for your records.</div>
          </div>
        </div>
      </div>
    </ModalShell>
  )
}

/* What YOUR TEAM sees — strictly internal, never sent to client */
function InternalBriefingModal({ onClose }) {
  return (
    <ModalShell onClose={onClose} maxWidth={700}>
      {/* Header — dark, confidential feel */}
      <div style={{ background: C.navy, padding: '20px 28px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 1 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
            <div style={{ background: '#EF444420', border: '1px solid #EF444440', borderRadius: 4, padding: '2px 8px', ...F.sans, fontSize: 10, fontWeight: 700, color: '#FCA5A5', letterSpacing: '0.06em' }}>
              INTERNAL ONLY — NOT SENT TO CLIENT
            </div>
          </div>
          <div style={{ ...F.sans, fontSize: 20, fontWeight: 800, color: '#fff' }}>AM Briefing · Apex Digital · April 2025</div>
        </div>
        <button onClick={onClose} style={{ width: 32, height: 32, borderRadius: '50%', background: 'rgba(255,255,255,0.1)', border: 'none', color: '#fff', cursor: 'pointer', fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'sans-serif' }}>×</button>
      </div>

      <div style={{ padding: '28px' }}>
        {/* "This is what your team sees" banner */}
        <div style={{ background: '#FEF3C7', border: '1px solid #FDE68A', borderRadius: 10, padding: '10px 16px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 1L1 14h14L8 1z" stroke="#D97706" strokeWidth="1.5" strokeLinejoin="round"/><path d="M8 6v4M8 11.5v.5" stroke="#D97706" strokeWidth="1.5" strokeLinecap="round"/></svg>
          <span style={{ ...F.sans, fontSize: 13, fontWeight: 600, color: '#92400E' }}>For your account managers only. Your client never sees this document.</span>
        </div>

        {/* Metrics */}
        <div className="sr-modal-metrics" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginBottom: 20 }}>
          {[
            { label: 'Impressions', value: '284K', delta: '↑ 12.4%', color: C.positive },
            { label: 'CTR', value: '6.4%', delta: '↑ 0.5pp', color: C.positive },
            { label: 'Conv. Rate', value: '2.3%', delta: '↑ 0.4pp', color: C.positive },
            { label: 'ROAS', value: '4.2×', delta: '↑ 0.6×', color: C.positive },
          ].map(m => (
            <div key={m.label} style={{ background: C.bgAlt, border: `1px solid ${C.border}`, borderRadius: 10, padding: '14px 16px' }}>
              <div style={{ ...F.sans, fontSize: 11, color: C.muted, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 4 }}>{m.label}</div>
              <div style={{ ...F.sans, fontSize: 24, fontWeight: 800, color: C.text, lineHeight: 1 }}>{m.value}</div>
              <div style={{ ...F.sans, fontSize: 12, color: m.color, fontWeight: 600, marginTop: 3 }}>{m.delta}</div>
            </div>
          ))}
        </div>

        {/* Anomaly flag */}
        <div style={{ background: '#FEF3C7', border: '1px solid #FDE68A', borderRadius: 10, padding: '14px 16px', marginBottom: 20, display: 'flex', gap: 12, alignItems: 'flex-start' }}>
          <span style={{ fontSize: 16, flexShrink: 0, marginTop: 1 }}>⚠️</span>
          <div>
            <div style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: '#92400E', marginBottom: 4 }}>Flag for team review</div>
            <div style={{ ...F.sans, fontSize: 13, color: '#92400E', lineHeight: 1.55 }}>Display CPM rose 18% vs. March — review placement exclusions before the next billing cycle. Don't surface this as a problem to the client; frame it as proactive housekeeping.</div>
          </div>
        </div>

        {/* Talking points */}
        <div style={{ background: C.bgAlt, border: `1px solid ${C.border}`, borderRadius: 12, padding: '18px 20px', marginBottom: 20 }}>
          <div style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: C.text, marginBottom: 4 }}>💬 Talking points for the client call</div>
          <p style={{ ...F.sans, fontSize: 12, color: C.muted, marginBottom: 14, lineHeight: 1.5 }}>How to frame this month's results. Use these in your own words — don't read them verbatim.</p>
          {[
            "Lead with the conversion win — 23.7% growth is a headline number clients remember and repeat.",
            "Explain the CPC improvement plainly: same budget, more customers. Frame it as smarter targeting, not luck.",
            "Introduce the branded campaign as a new growth lever. Propose a 20% budget increase — the data supports it.",
            "Acknowledge the display CPM rise yourself before they ask. It shows you're on top of the details.",
          ].map((point, i) => (
            <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', marginBottom: i < 3 ? 10 : 0, padding: '10px 12px', background: '#fff', borderRadius: 8, border: `1px solid ${C.border}` }}>
              <span style={{ ...F.sans, fontSize: 13, color: C.accent, fontWeight: 800, minWidth: 20 }}>{i + 1}.</span>
              <span style={{ ...F.sans, fontSize: 13, color: '#334155', lineHeight: 1.55 }}>{point}</span>
            </div>
          ))}
        </div>

        {/* Predicted Q&A */}
        <div>
          <div style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: C.text, marginBottom: 4 }}>🔮 Questions your client will likely ask — with prepared answers</div>
          <p style={{ ...F.sans, fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
            AI predicted these based on this month's data. Review before the call so nothing catches you off guard.
          </p>
          {[
            { q: 'Our impressions dropped slightly — should we be worried?', a: 'Total impressions fell 3% as we shifted budget toward higher-intent keywords. Conversions went up 23.7% as a result. We\'re reaching fewer people, but the right ones.' },
            { q: 'Why did spend go up if efficiency improved?', a: 'Spend increased modestly while conversions rose 23.7% — that\'s the definition of improved efficiency. Every extra dollar went to Shopping campaigns where your conversion rate is highest.' },
            { q: 'What should we expect next month?', a: 'We\'ll hold the current allocation and watch for CPA creep. If the first two weeks of May hold, we\'d recommend a 10–15% budget increase to capture the demand that\'s clearly there.' },
          ].map((pq, i) => (
            <div key={i} style={{ background: `${C.navy}07`, border: `1px solid ${C.navy}18`, borderRadius: 10, padding: '14px 16px', marginBottom: 10 }}>
              <div style={{ display: 'flex', gap: 10, marginBottom: 8 }}>
                <span style={{ ...F.sans, fontSize: 10, fontWeight: 700, color: C.navy, background: `${C.navy}15`, padding: '2px 8px', borderRadius: 10, whiteSpace: 'nowrap', flexShrink: 0 }}>Q{i + 1}</span>
                <div style={{ ...F.sans, fontSize: 14, fontWeight: 600, color: C.text, lineHeight: 1.4 }}>"{pq.q}"</div>
              </div>
              <div style={{ display: 'flex', gap: 10 }}>
                <span style={{ ...F.sans, fontSize: 13, fontWeight: 700, color: C.positive, flexShrink: 0 }}>→</span>
                <div style={{ ...F.sans, fontSize: 13, color: '#334155', lineHeight: 1.6 }}>{pq.a}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div style={{ marginTop: 24, background: `${C.navy}08`, border: `1px solid ${C.navy}18`, borderRadius: 10, padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: 18 }}>🔒</span>
          <div style={{ ...F.sans, fontSize: 12, color: C.muted, lineHeight: 1.5 }}>
            This briefing is <strong>never shared with clients.</strong> Your client receives only the polished client report — separate document, separate delivery.
          </div>
        </div>
      </div>
    </ModalShell>
  )
}

/* ─────────── Report type cards ─────────── */

const REPORT_TYPES = [
  {
    id: 'client',
    badge: 'Client-facing',
    badgeColor: C.accent,
    title: 'Client Performance Report',
    desc: 'A polished, jargon-free narrative designed to impress clients and build trust. Focuses on outcomes and stories — not technical data.',
    highlights: [
      'Plain-English AI narrative — generated live in under 60 seconds',
      'Top-line metric highlights from your Google Ads data',
      'AI-predicted client questions + prepared answers',
      'Emailed to clients automatically — no login required',
      'White-labeled with your agency branding',
    ],
    Preview: ClientReportPreview,
    cta: 'View client report',
    canOpen: true,
  },
  {
    id: 'internal',
    badge: 'Internal only',
    badgeColor: C.navy,
    title: 'Internal AM Briefing',
    desc: 'Strictly for your team — never sent to clients. Talking points, anomaly flags, predicted client questions, and prepared answers so every AM walks into the call ready.',
    highlights: [
      'Talking points — how to frame every result in plain English',
      'Predicted client questions + word-for-word prepared answers',
      'Anomaly detection & team flags before the client spots them',
      'Campaign-level technical breakdown',
      'Confidential — your client never sees this document',
    ],
    Preview: InternalReportPreview,
    cta: 'View internal briefing',
    canOpen: true,
  },
  {
    id: 'executive',
    badge: 'Executive',
    badgeColor: '#7C3AED',
    title: 'Quarterly Executive Summary',
    desc: 'A high-level roll-up across all campaigns for agency directors and client stakeholders. QoQ comparisons, strategic wins, and a one-page board-ready format.',
    highlights: [
      'Multi-campaign roll-up with QoQ & YoY comparisons',
      'Key wins and strategic flags in plain English',
      'One-page format — perfect for QBRs',
      'Generated from the same data as monthly reports',
      'Ideal for retainer renewal conversations',
    ],
    Preview: ExecutiveSummaryPreview,
    cta: 'View executive summary',
    canOpen: false,
  },
]

/* ─────────── Page ─────────── */

export default function SampleReportPage() {
  const [openModal, setOpenModal] = useState(null)
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const h = () => setScrolled(window.scrollY > 20)
    window.addEventListener('scroll', h)
    return () => window.removeEventListener('scroll', h)
  }, [])

  return (
    <div style={{ ...F.sans, color: C.text, background: C.bgAlt, WebkitFontSmoothing: 'antialiased', minHeight: '100vh' }}>
      <style>{PAGE_CSS}</style>

      {/* Nav */}
      <nav className={`sr-nav${scrolled ? ' scrolled' : ''}`} style={{ position: 'sticky', top: 0, zIndex: 100 }}>
        <div style={{ maxWidth: 1180, margin: '0 auto', padding: '0 32px', height: 64, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 32 }}>
            <Logo />
            <div style={{ display: 'flex', gap: 4 }}>
              <Link to="/" className="sr-nav-link" style={F.sans}>Home</Link>
              <Link to="/pricing" className="sr-nav-link" style={F.sans}>Pricing</Link>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <Link to="/sign-in" style={{ ...F.sans, fontSize: 14, fontWeight: 500, color: C.muted, padding: '8px 14px', textDecoration: 'none' }}>Sign in</Link>
            <Link to="/sign-up" style={{ ...F.sans, fontSize: 14, fontWeight: 700, color: '#fff', background: C.accent, textDecoration: 'none', padding: '9px 20px', borderRadius: 8 }}>Start Free Trial</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <div style={{ background: C.bg, borderBottom: `1px solid ${C.border}`, padding: '56px 32px 48px' }}>
        <div style={{ maxWidth: 720, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: `${C.accent}12`, border: `1px solid ${C.accent}25`, borderRadius: 20, padding: '4px 14px', marginBottom: 20, ...F.sans, fontSize: 13, fontWeight: 600, color: C.accent }}>
            Sample reports
          </div>
          <h1 style={{ ...F.sans, fontSize: 40, fontWeight: 800, letterSpacing: '-0.025em', lineHeight: 1.1, marginBottom: 14 }}>
            See what your clients will receive
          </h1>
          <p style={{ ...F.sans, fontSize: 17, color: C.muted, lineHeight: 1.65, maxWidth: 540, margin: '0 auto' }}>
            retainr generates three types of reports from the same Google Ads data — each written by AI in real-time, tailored to a different audience.
          </p>
        </div>
      </div>

      {/* Report type cards */}
      <div style={{ maxWidth: 1180, margin: '0 auto', padding: '56px 32px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          {REPORT_TYPES.map(({ id, badge, badgeColor, title, desc, highlights, Preview, cta, canOpen }, i) => (
            <div key={id} className="sr-report-card" style={{ display: 'grid', gridTemplateColumns: i % 2 === 0 ? '1fr 420px' : '420px 1fr' }}>
              {/* Info side */}
              <div style={{
                padding: '40px 44px', display: 'flex', flexDirection: 'column', justifyContent: 'center',
                order: i % 2 === 0 ? 0 : 1,
              }}>
                <div style={{
                  display: 'inline-flex', alignItems: 'center', background: `${badgeColor}15`,
                  borderRadius: 6, padding: '3px 10px', marginBottom: 16, alignSelf: 'flex-start',
                }}>
                  <span style={{ ...F.sans, fontSize: 11, fontWeight: 700, color: badgeColor, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{badge}</span>
                </div>
                <h2 style={{ ...F.sans, fontSize: 22, fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 10 }}>{title}</h2>
                <p style={{ ...F.sans, fontSize: 15, color: C.muted, lineHeight: 1.65, marginBottom: 24 }}>{desc}</p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 28 }}>
                  {highlights.map(h => (
                    <div key={h} style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{ flexShrink: 0, marginTop: 2 }}>
                        <circle cx="7" cy="7" r="6.5" fill={`${C.accent}15`} />
                        <path d="M4.5 7l1.5 1.5L9.5 5" stroke={C.accent} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                      <span style={{ ...F.sans, fontSize: 14, color: '#334155' }}>{h}</span>
                    </div>
                  ))}
                </div>
                <button
                  className="sr-view-btn"
                  onClick={() => canOpen ? setOpenModal(id) : null}
                  style={{ alignSelf: 'flex-start', opacity: canOpen ? 1 : 0.6, cursor: canOpen ? 'pointer' : 'default' }}
                  title={canOpen ? undefined : 'Full report available in your account'}
                >
                  {canOpen ? `${cta} →` : `${cta} (in your account)`}
                </button>
              </div>

              {/* Preview side */}
              <div className="sr-preview-col" style={{
                background: C.bgAlt, padding: '28px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                borderLeft: i % 2 === 0 ? `1px solid ${C.border}` : 'none',
                borderRight: i % 2 !== 0 ? `1px solid ${C.border}` : 'none',
                order: i % 2 === 0 ? 1 : 0,
              }}>
                <div style={{ width: '100%', maxWidth: 340 }}>
                  <Preview />
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Real-time AI callout */}
        <div style={{ marginTop: 48, background: `${C.accent}08`, border: `1px solid ${C.accent}18`, borderRadius: 14, padding: '28px 32px', display: 'flex', alignItems: 'center', gap: 24, flexWrap: 'wrap' }}>
          <div style={{ fontSize: 36 }}>⚡</div>
          <div>
            <div style={{ ...F.sans, fontSize: 16, fontWeight: 800, color: C.text, marginBottom: 6 }}>Generated on-demand in real-time</div>
            <p style={{ ...F.sans, fontSize: 14, color: C.muted, lineHeight: 1.6, margin: 0 }}>
              Every report is created fresh from your live Google Ads data the moment you request it — not from templates or cached text.
              AI reads your actual account metrics, identifies what changed and why, and writes a unique narrative in under 60 seconds.
            </p>
          </div>
          <div style={{ display: 'flex', gap: 20, flexShrink: 0, flexWrap: 'wrap' }}>
            {[['47 sec', 'avg generation time'], ['3 reports', 'per request (client, internal, exec)'], ['100%', 'live from your account']].map(([v, l]) => (
              <div key={l} style={{ textAlign: 'center' }}>
                <div style={{ ...F.sans, fontSize: 22, fontWeight: 800, color: C.accent, letterSpacing: '-0.02em' }}>{v}</div>
                <div style={{ ...F.sans, fontSize: 11, color: C.muted, maxWidth: 80 }}>{l}</div>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div style={{ marginTop: 48, background: C.accent, borderRadius: 16, padding: '48px', textAlign: 'center' }}>
          <h2 style={{ ...F.sans, fontSize: 32, fontWeight: 800, color: '#fff', letterSpacing: '-0.025em', marginBottom: 10 }}>
            Ready to generate reports like these?
          </h2>
          <p style={{ ...F.sans, fontSize: 16, color: 'rgba(255,255,255,0.65)', marginBottom: 28, lineHeight: 1.6 }}>
            Connect your Google Ads account and get your first real-time AI report in under 60 seconds.
          </p>
          <div style={{ display: 'flex', justifyContent: 'center', gap: 12, flexWrap: 'wrap' }}>
            <Link to="/sign-up" style={{ ...F.sans, padding: '13px 28px', borderRadius: 10, background: '#fff', color: C.accent, fontSize: 15, fontWeight: 700, textDecoration: 'none' }}>
              Start Free Trial
            </Link>
            <Link to="/sign-in" style={{ ...F.sans, padding: '13px 24px', borderRadius: 10, border: '2px solid rgba(255,255,255,0.3)', color: '#fff', fontSize: 15, fontWeight: 600, textDecoration: 'none' }}>
              Sign in
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer style={{ padding: '40px 32px', background: C.navy, color: 'rgba(255,255,255,0.5)' }}>
        <div style={{ maxWidth: 1180, margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
          <Logo dark />
          <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap' }}>
            {[['/', 'Product'], ['/pricing', 'Pricing'], ['/sample-reports', 'Sample Reports'], ['/privacy', 'Privacy'], ['/terms', 'Terms']].map(([href, label]) => (
              <Link key={href} to={href} style={{ ...F.sans, fontSize: 13, color: 'rgba(255,255,255,0.45)', textDecoration: 'none' }}>{label}</Link>
            ))}
          </div>
          <span style={{ ...F.sans, fontSize: 12 }}>© 2025 retainr. All rights reserved.</span>
        </div>
      </footer>

      {/* Modals */}
      {openModal === 'client'   && <ClientReportModal     onClose={() => setOpenModal(null)} />}
      {openModal === 'internal' && <InternalBriefingModal onClose={() => setOpenModal(null)} />}
    </div>
  )
}
