// BindIQ state configuration
// Each entry defines the copy, form names, and insurer context for a supported state.

export const STATES = {
  FL: {
    name: 'Florida',
    abbr: 'FL',
    insurer: 'Citizens Property Insurance',
    program: 'Citizens',
    forms: ['OIR-B1-1802 Wind Mitigation', '4-Point Inspection'],
    formShort: '4-point · Wind mitigation OIR-B1-1802',
    formHint: 'Paste the full text of a 4-point or wind mitigation report (OIR-B1-1802).',
    uploadHint: '4-point + wind mit together',
    sampleCity: 'Naples, FL',
    sampleLabel: 'Wind mitigation · Naples, FL',
    scoreSubtitle: 'Standard FL carrier placement likelihood',
    carrierAbbr: 'FL',
    paywallForms: 'OIR-B1-1802 + 4-point',
    entryDesc: 'Upload a 4-point or wind mitigation PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'Florida 4-point · Wind mitigation OIR-B1-1802',
    sampleType: 'Wind mitigation',
    intakePlaceholder: '123 Bayfront Dr, Miami, FL 33101',
    intakeUploadText: 'If you have a Florida 4-point or wind mitigation inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'Florida agents lose hours every week quoting properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit — so you only quote risks that have a real chance of binding.',
    landingUploadCaption: 'Upload any Florida 4-point or wind mitigation report PDF. Works with any inspection company\'s format — no reformatting, no manual data entry.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real Florida underwriting rules.',
    landingCarrierNote: 'Most Florida carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most FL carriers will not bind on either panel brand. Both are known fire hazards — virtually every standard market requires replacement before quoting.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard FL carriers. Catching this before the quote prevents a wasted submission entirely.',
    landingFlagPoly: 'Many FL carriers exclude water damage or require replacement. Catching this before submission prevents the client call no one wants to make.',
    landingFlagRoof: 'Most FL carriers require a roof inspection or condition letter for roofs over 20–25 years. Age and condition are flagged automatically so you can set expectations before the quote goes out.',
    landingAgentNote: 'Most Florida agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with most standard Florida 4-point and wind mitigation reports. If the PDF contains selectable text, it processes instantly.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built specifically for Florida underwriting workflows — critical risk indicators are detected using a rules engine, not guesswork.',
  },

  TX: {
    name: 'Texas',
    abbr: 'TX',
    insurer: 'TWIA (Texas Windstorm Insurance Association)',
    program: 'TWIA',
    forms: ['TWIA WPI-8 Windstorm Inspection', '4-Point Inspection'],
    formShort: 'WPI-8 windstorm · 4-point inspection',
    formHint: 'Paste the full text of a WPI-8 windstorm or 4-point inspection report.',
    uploadHint: 'WPI-8 + 4-point together',
    sampleCity: 'Galveston, TX',
    sampleLabel: 'Windstorm inspection · Galveston, TX',
    scoreSubtitle: 'TWIA / TX carrier placement likelihood',
    carrierAbbr: 'TX',
    paywallForms: 'TWIA WPI-8 + 4-point',
    entryDesc: 'Upload a WPI-8 windstorm or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'TWIA WPI-8 windstorm · 4-point inspection',
    sampleType: 'Windstorm inspection',
    intakePlaceholder: '123 Seawall Blvd, Galveston, TX 77550',
    intakeUploadText: 'If you have a TWIA WPI-8 windstorm or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'Texas coastal agents lose hours every week quoting properties TWIA won\'t accept. BindIQ identifies underwriting issues before you submit — so you only quote risks that have a real chance of binding.',
    landingUploadCaption: 'Upload any Texas WPI-8 windstorm or 4-point inspection report PDF. Works with any inspection company\'s format — no reformatting, no manual data entry.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real Texas coastal underwriting rules.',
    landingCarrierNote: 'Most TX coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most TX carriers will not bind on either panel brand. Both are known fire hazards — virtually every standard market requires replacement before quoting.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard TX carriers. Catching this before the quote prevents a wasted submission entirely.',
    landingFlagPoly: 'Many TX carriers exclude water damage or require replacement. Catching this before submission prevents the client call no one wants to make.',
    landingFlagRoof: 'Most TX carriers require a roof inspection or condition letter for roofs over 20–25 years. Age and condition are flagged automatically so you can set expectations before the quote goes out.',
    landingAgentNote: 'Most Texas coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with TWIA WPI-8 windstorm reports and standard Texas 4-point inspections. If the PDF contains selectable text, it processes instantly.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built specifically for Texas coastal underwriting workflows — critical risk indicators are detected using a rules engine, not guesswork.',
  },

  LA: {
    name: 'Louisiana',
    abbr: 'LA',
    insurer: 'Louisiana Citizens Property Insurance',
    program: 'LA Citizens',
    forms: ['Louisiana Wind & Hail Inspection', '4-Point Inspection'],
    formShort: 'Wind & hail · 4-point inspection',
    formHint: 'Paste the full text of a wind & hail or 4-point inspection report.',
    uploadHint: 'Wind & hail + 4-point together',
    sampleCity: 'New Orleans, LA',
    sampleLabel: 'Wind & hail inspection · New Orleans, LA',
    scoreSubtitle: 'LA Citizens / carrier placement likelihood',
    carrierAbbr: 'LA',
    paywallForms: 'Louisiana wind & hail + 4-point',
    entryDesc: 'Upload a wind & hail or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'Louisiana wind & hail · 4-point inspection',
    sampleType: 'Wind & hail inspection',
    intakePlaceholder: '123 Magazine St, New Orleans, LA 70115',
    intakeUploadText: 'If you have a Louisiana wind & hail or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'Louisiana agents lose hours every week quoting coastal properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit — so you only quote risks that have a real chance of binding.',
    landingUploadCaption: 'Upload any Louisiana wind & hail or 4-point inspection report PDF. Works with any inspection company\'s format.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real Louisiana underwriting rules.',
    landingCarrierNote: 'Most Louisiana coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most LA carriers will not bind on either panel brand. Both are known fire hazards — virtually every standard market requires replacement before quoting.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard LA carriers.',
    landingFlagPoly: 'Many LA carriers exclude water damage or require replacement.',
    landingFlagRoof: 'Most LA carriers require a roof inspection or condition letter for roofs over 20–25 years.',
    landingAgentNote: 'Most Louisiana coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with Louisiana Citizens wind & hail reports and standard 4-point inspections.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built for Louisiana coastal underwriting workflows.',
  },

  SC: {
    name: 'South Carolina',
    abbr: 'SC',
    insurer: 'SC Wind & Hail Underwriting Association (SCWHUA)',
    program: 'SCWHUA',
    forms: ['SCWHUA Wind & Hail Inspection', '4-Point Inspection'],
    formShort: 'Wind & hail · 4-point inspection',
    formHint: 'Paste the full text of a wind & hail or 4-point inspection report.',
    uploadHint: 'Wind & hail + 4-point together',
    sampleCity: 'Charleston, SC',
    sampleLabel: 'Wind & hail inspection · Charleston, SC',
    scoreSubtitle: 'SCWHUA / SC carrier placement likelihood',
    carrierAbbr: 'SC',
    paywallForms: 'SCWHUA wind & hail + 4-point',
    entryDesc: 'Upload a wind & hail or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'SCWHUA wind & hail · 4-point inspection',
    sampleType: 'Wind & hail inspection',
    intakePlaceholder: '123 King St, Charleston, SC 29401',
    intakeUploadText: 'If you have a SCWHUA wind & hail or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'South Carolina coastal agents lose hours every week quoting properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit.',
    landingUploadCaption: 'Upload any SCWHUA wind & hail or 4-point inspection report PDF.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real South Carolina underwriting rules.',
    landingCarrierNote: 'Most SC coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most SC carriers will not bind on either panel brand — both require replacement before any standard market will quote.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard SC carriers.',
    landingFlagPoly: 'Many SC carriers exclude water damage or require polybutylene replacement.',
    landingFlagRoof: 'Most SC carriers require a roof inspection for roofs over 20–25 years.',
    landingAgentNote: 'Most South Carolina coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with SCWHUA wind & hail reports and standard 4-point inspections.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built for South Carolina coastal underwriting workflows.',
  },

  AL: {
    name: 'Alabama',
    abbr: 'AL',
    insurer: 'Alabama Insurance Underwriting Association (AIUA)',
    program: 'AIUA',
    forms: ['AIUA Wind & Hail Inspection', '4-Point Inspection'],
    formShort: 'Wind & hail · 4-point inspection',
    formHint: 'Paste the full text of a wind & hail or 4-point inspection report.',
    uploadHint: 'Wind & hail + 4-point together',
    sampleCity: 'Mobile, AL',
    sampleLabel: 'Wind & hail inspection · Mobile, AL',
    scoreSubtitle: 'AIUA / AL carrier placement likelihood',
    carrierAbbr: 'AL',
    paywallForms: 'AIUA wind & hail + 4-point',
    entryDesc: 'Upload a wind & hail or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'AIUA wind & hail · 4-point inspection',
    sampleType: 'Wind & hail inspection',
    intakePlaceholder: '123 Government St, Mobile, AL 36602',
    intakeUploadText: 'If you have an AIUA wind & hail or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'Alabama Gulf Coast agents lose hours quoting properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit.',
    landingUploadCaption: 'Upload any AIUA wind & hail or 4-point inspection report PDF.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real Alabama coastal underwriting rules.',
    landingCarrierNote: 'Most AL coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most AL carriers will not bind on either panel brand — replacement required before standard markets will quote.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard AL carriers.',
    landingFlagPoly: 'Many AL carriers exclude water damage or require polybutylene replacement.',
    landingFlagRoof: 'Most AL carriers require a roof inspection for roofs over 20–25 years.',
    landingAgentNote: 'Most Alabama coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with AIUA wind & hail reports and standard 4-point inspections.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built for Alabama coastal underwriting workflows.',
  },

  MS: {
    name: 'Mississippi',
    abbr: 'MS',
    insurer: 'Mississippi Windstorm Underwriting Association (MWUA)',
    program: 'MWUA',
    forms: ['MWUA Windstorm Inspection', '4-Point Inspection'],
    formShort: 'Windstorm · 4-point inspection',
    formHint: 'Paste the full text of a windstorm or 4-point inspection report.',
    uploadHint: 'Windstorm + 4-point together',
    sampleCity: 'Gulfport, MS',
    sampleLabel: 'Windstorm inspection · Gulfport, MS',
    scoreSubtitle: 'MWUA / MS carrier placement likelihood',
    carrierAbbr: 'MS',
    paywallForms: 'MWUA windstorm + 4-point',
    entryDesc: 'Upload a windstorm or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'MWUA windstorm · 4-point inspection',
    sampleType: 'Windstorm inspection',
    intakePlaceholder: '123 Pass Rd, Gulfport, MS 39501',
    intakeUploadText: 'If you have a MWUA windstorm or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'Mississippi Gulf Coast agents lose hours quoting properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit.',
    landingUploadCaption: 'Upload any MWUA windstorm or 4-point inspection report PDF.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real Mississippi coastal underwriting rules.',
    landingCarrierNote: 'Most MS coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most MS carriers will not bind on either panel brand — replacement required before standard markets will quote.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard MS carriers.',
    landingFlagPoly: 'Many MS carriers exclude water damage or require polybutylene replacement.',
    landingFlagRoof: 'Most MS carriers require a roof inspection for roofs over 20–25 years.',
    landingAgentNote: 'Most Mississippi coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with MWUA windstorm reports and standard 4-point inspections.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built for Mississippi coastal underwriting workflows.',
  },

  NC: {
    name: 'North Carolina',
    abbr: 'NC',
    insurer: 'NC Joint Underwriting Association (NCJUA) / Beach Plan',
    program: 'NCJUA',
    forms: ['NCJUA Wind-Only Inspection', '4-Point Inspection'],
    formShort: 'Wind-only · 4-point inspection',
    formHint: 'Paste the full text of a wind-only or 4-point inspection report.',
    uploadHint: 'Wind-only + 4-point together',
    sampleCity: 'Wilmington, NC',
    sampleLabel: 'Wind-only inspection · Wilmington, NC',
    scoreSubtitle: 'NCJUA Beach Plan / NC carrier placement likelihood',
    carrierAbbr: 'NC',
    paywallForms: 'NCJUA wind-only + 4-point',
    entryDesc: 'Upload a wind-only or 4-point PDF. Get an instant bind likelihood score and every underwriting red flag in seconds.',
    footerNote: 'NCJUA wind-only · 4-point inspection',
    sampleType: 'Wind-only inspection',
    intakePlaceholder: '123 Market St, Wilmington, NC 28401',
    intakeUploadText: 'If you have a NCJUA wind-only or 4-point inspection report, upload it here for a more accurate BindIQ Score. Otherwise, we\'ll estimate from your answers.',
    landingHeroBody: 'North Carolina coastal agents lose hours quoting properties carriers won\'t accept. BindIQ identifies underwriting issues before you submit.',
    landingUploadCaption: 'Upload any NCJUA wind-only or 4-point inspection report PDF.',
    landingScoreCaption: 'Every report gets scored 0–100 based on real North Carolina coastal underwriting rules.',
    landingCarrierNote: 'Most NC coastal carriers will not bind this risk without remediation.',
    landingFlagZinsco: 'Most NC carriers will not bind on either panel brand — replacement required before standard markets will quote.',
    landingFlagKnob: 'Knob-and-tube is uninsurable with virtually all standard NC carriers.',
    landingFlagPoly: 'Many NC carriers exclude water damage or require polybutylene replacement.',
    landingFlagRoof: 'Most NC carriers require a roof inspection for roofs over 20–25 years.',
    landingAgentNote: 'Most North Carolina coastal agents process 20–100 reports per month.',
    landingFaqFormats: 'Yes — BindIQ works with NCJUA wind-only reports and standard 4-point inspections.',
    landingFaqAccuracy: 'Highly accurate for standard inspection formats. Built for North Carolina coastal underwriting workflows.',
  },
}

export const DEFAULT_STATE = 'FL'
export const SUPPORTED_STATES = Object.keys(STATES)

export function getStateConfig(code) {
  return STATES[code] || STATES[DEFAULT_STATE]
}
