import { useRef, useState } from 'react'
import { inspectPaperbackCover, repairPaperbackCover, downloadPdf, requiredPaperbackCoverSize } from './coverEngine'
import { inspectInteriorPdf, inspectEpub } from './bookValidators'

const options=[['ebook-manuscript','eBook manuscript','Validated EPUB'],['paperback-manuscript','Paperback manuscript','Print-ready interior PDF'],['hardcover-manuscript','Hardcover manuscript','Hardcover interior PDF'],['ebook-cover','eBook cover','Amazon-ready JPG'],['paperback-cover','Paperback cover','Full-wrap cover PDF'],['hardcover-cover','Hardcover cover','Hardcover wrap PDF']]
const priceFor=n=>n?Math.min(59,19+(n-1)*10):0
const Check=()=> <span className="check">✓</span>
const Fail=()=> <span className="x">×</span>
function Logo(){return <div className="logo"><span>P</span><b>PublishReady</b></div>}
function Header(){return <header className="site-header"><div className="wrap nav"><a href="#top"><Logo/></a><nav><a href="#checker">File Checker</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><a className="primary small" href="#checker">Check My Files</a></div></header>}

function Pricing(){const[selected,setSelected]=useState(['ebook-manuscript','ebook-cover']);const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);return <section id="pricing" className="configurator wrap"><div className="config-copy"><span className="eyebrow">Transparent pricing</span><h2>Select only what you need.</h2><p>First deliverable $19. Each additional deliverable $10. Complete book capped at $59.</p></div><div className="config-card"><div className="config-groups">{['Manuscript','Covers'].map((group,gi)=><div className="config-group" key={group}><h3>{group}</h3>{options.slice(gi?3:0,gi?6:3).map(([id,label,detail])=><label key={id} className={selected.includes(id)?'option selected':'option'}><input type="checkbox" checked={selected.includes(id)} onChange={()=>toggle(id)}/><span className="box">✓</span><span><b>{label}</b><small>{detail}</small></span></label>)}</div>)}</div><aside className="price-summary"><p>Your publishing package</p><div className="selection-list">{selected.length?selected.map(id=><span key={id}><Check/>{options.find(x=>x[0]===id)[1]}</span>):<small>Select at least one item.</small>}</div><div className="total"><span>Total</span><strong>${priceFor(selected.length)}</strong></div><small>Paid exports remain disabled during validation beta.</small><button className="primary wide" disabled>Coming after beta</button></aside></div></section>}

async function inspectDocx(file){if(!window.JSZip)throw new Error('Document reader failed to load.');const zip=await window.JSZip.loadAsync(file);const entry=zip.file('word/document.xml');if(!entry)throw new Error('This is not a valid DOCX file.');const doc=new DOMParser().parseFromString(await entry.async('string'),'application/xml');const paras=[...doc.getElementsByTagNameNS('*','p')];let words=0,paragraphs=0;const chapters=[];paras.forEach(p=>{const text=[...p.getElementsByTagNameNS('*','t')].map(n=>n.textContent).join('').trim();if(!text)return;paragraphs++;words+=text.split(/\s+/).filter(Boolean).length;const style=p.getElementsByTagNameNS('*','pStyle')[0]?.getAttribute('w:val')||'';if(/heading1|chapter|title/i.test(style)||(/^(chapter|prologue|epilogue|introduction|part)\b/i.test(text)&&text.length<90))chapters.push(text)});return{words,paragraphs,chapters:[...new Set(chapters)]}}

function Result({pass,title,children}){return <div className={pass?'result pass':'result fail'}><div className="result-title"><b>{pass?'PASS':title||'ISSUES FOUND'}</b></div>{children}</div>}

function FileChecker(){
 const coverRef=useRef(),docxRef=useRef(),interiorRef=useRef(),epubRef=useRef()
 const[trim,setTrim]=useState('6x9'),[pages,setPages]=useState(263),[paper,setPaper]=useState('White'),[error,setError]=useState('')
 const[cover,setCover]=useState(null),[coverResult,setCoverResult]=useState(null),[repairing,setRepairing]=useState(false)
 const[docx,setDocx]=useState(null),[docxResult,setDocxResult]=useState(null)
 const[interior,setInterior]=useState(null),[interiorResult,setInteriorResult]=useState(null)
 const[epub,setEpub]=useState(null),[epubResult,setEpubResult]=useState(null)
 const[tw,th]=trim.split('x').map(Number);const required=requiredPaperbackCoverSize({trimWidth:tw,trimHeight:th,pageCount:Number(pages),paper})
 const guard=async(fn)=>{setError('');try{return await fn()}catch(e){setError(e.message);return null}}
 async function checkCover(file){if(!file)return;setCover(file);setCoverResult(await guard(()=>inspectPaperbackCover(file,{trimWidth:tw,trimHeight:th,pageCount:Number(pages),paper})))}
 async function fixCover(){setRepairing(true);const bytes=await guard(()=>repairPaperbackCover(coverResult));if(bytes)downloadPdf(bytes,`${cover.name.replace(/\.pdf$/i,'')}-publishready-fixed.pdf`);setRepairing(false)}
 async function checkDocx(file){if(!file)return;setDocx(file);setDocxResult(await guard(()=>inspectDocx(file)))}
 async function checkInterior(file){if(!file)return;setInterior(file);setInteriorResult(await guard(()=>inspectInteriorPdf(file,{trimWidth:tw,trimHeight:th})))}
 async function checkEpub(file){if(!file)return;setEpub(file);setEpubResult(await guard(()=>inspectEpub(file)))}
 const Upload=({refObj,accept,onChange,file,label,sub})=><button className="drop" onClick={()=>refObj.current.click()}><input ref={refObj} hidden type="file" accept={accept} onChange={e=>onChange(e.target.files?.[0])}/><strong>{file?file.name:label}</strong><span>{file?'Click to replace':sub}</span></button>
 return <section id="checker" className="checker wrap"><div className="checker-heading"><span className="eyebrow">Free validation beta</span><h2>Check the files you already have.</h2><p>PublishReady reads the actual files locally in your browser. It does not just describe KDP rules.</p></div><div className="form cover-settings global-settings"><label>Trim size<select value={trim} onChange={e=>setTrim(e.target.value)}><option value="6x9">6 × 9 in</option><option value="5.5x8.5">5.5 × 8.5 in</option><option value="5x8">5 × 8 in</option></select></label><label>Final page count<input type="number" min="24" value={pages} onChange={e=>setPages(e.target.value)}/></label><label>Paper<select value={paper} onChange={e=>setPaper(e.target.value)}><option>White</option><option>Cream</option></select></label></div><div className="checker-grid">
 <article className="checker-panel"><h3>Paperback cover PDF</h3><div className="required-size"><span>Required</span><b>{required.width.toFixed(3)} × {required.height.toFixed(3)} in</b><small>Spine {required.spine.toFixed(3)} in</small></div><Upload refObj={coverRef} accept="application/pdf,.pdf" onChange={checkCover} file={cover} label="Choose paperback cover PDF" sub="One-page PDF"/>{coverResult&&<Result pass={coverResult.pass} title="BLOCKING DIMENSION ISSUE">{coverResult.pass?<p><Check/>Canvas dimensions match KDP requirements.</p>:coverResult.issues.map(i=><p key={i.code}><Fail/>{i.message}</p>)}{coverResult.canAutoFix&&<><p className="warning">Repair rescales and centers the supplied cover. Review for cropping before submission.</p><button className="primary" onClick={fixCover} disabled={repairing}>{repairing?'Repairing…':'Fix & Download PDF'}</button></>}</Result>}</article>
 <article className="checker-panel"><h3>Print interior PDF</h3><Upload refObj={interiorRef} accept="application/pdf,.pdf" onChange={checkInterior} file={interior} label="Choose interior PDF" sub="Paperback or hardcover interior"/>{interiorResult&&<Result pass={interiorResult.pass}>{interiorResult.pass?<p><Check/>{interiorResult.pageCount} pages at {interiorResult.actual.width.toFixed(3)} × {interiorResult.actual.height.toFixed(3)} in.</p>:interiorResult.issues.map((i,n)=><p key={n}><Fail/>{i}</p>)}</Result>}</article>
 <article className="checker-panel"><h3>Kindle EPUB</h3><Upload refObj={epubRef} accept=".epub,application/epub+zip" onChange={checkEpub} file={epub} label="Choose EPUB" sub="EPUB file"/>{epubResult&&<Result pass={epubResult.pass}>{epubResult.pass?<><p><Check/>{epubResult.title||'Title'} by {epubResult.creator||'Unknown author'}</p><p><Check/>{epubResult.spineCount} reading-order items and navigation found.</p></>:epubResult.issues.map((i,n)=><p key={n}><Fail/>{i}</p>)}</Result>}</article>
 <article className="checker-panel"><h3>Manuscript DOCX</h3><Upload refObj={docxRef} accept=".docx" onChange={checkDocx} file={docx} label="Choose manuscript DOCX" sub="DOCX file"/>{docxResult&&<div className="docx-results"><div><b>{docxResult.words.toLocaleString()}</b><span>words</span></div><div><b>{docxResult.paragraphs.toLocaleString()}</b><span>paragraphs</span></div><div><b>{docxResult.chapters.length}</b><span>headings</span></div><p><Check/>Read successfully in your browser.</p></div>}</article>
 </div>{error&&<p className="error">{error}</p>}</section>}

function App(){return <><Header/><main id="top"><section className="hero wrap"><div><span className="eyebrow">Built for independent authors</span><h1>Your book is done.<br/><span>We help you publish it right.</span></h1><p className="lead">Check your cover, interior, EPUB, and manuscript before Amazon does.</p><div className="hero-actions"><a className="primary" href="#checker">Check My Files →</a><a className="secondary" href="#pricing">See Pricing</a></div><div className="trust"><span>✓ Files stay local</span><span>✓ Deterministic checks</span><span>✓ No subscription</span></div></div><div className="hero-proof"><div className="proof-badge">REAL FILE CHECKS</div><h3>Four production checks</h3><p>Cover PDF · Interior PDF · EPUB · DOCX</p><strong>No canned rejection required.</strong><p className="proof-note">The beta reads the files themselves and reports exact, reproducible failures.</p></div></section><FileChecker/><Pricing/><section id="faq" className="faq wrap"><h2>Questions, answered simply.</h2><details><summary>Is this just ChatGPT advice?<span>+</span></summary><p>No. The app reads PDF page boxes, EPUB package files, reading order, metadata, and DOCX structure directly.</p></details><details><summary>Does a passing result guarantee KDP approval?<span>+</span></summary><p>Not yet. Current checks cover dimensions and structural integrity. Visual safe zones, barcode clearance, font embedding, image resolution, and transparency checks are still being added.</p></details><details><summary>Are my files uploaded?<span>+</span></summary><p>No. Current beta processing happens locally in your browser.</p></details></section></main><footer className="wrap"><Logo/><span>© 2026 PublishReady · Validation Beta</span></footer></>}
export default App
